package com.example.mindwave.fl

import android.content.Context
import android.content.Intent
import android.content.IntentFilter
import android.os.BatteryManager
import android.os.SystemClock
import android.os.Trace
import android.util.Log
import androidx.work.*
import com.example.mindwave.data.AuthRepository
import com.example.mindwave.data.MindWaveDatabase
import com.example.mindwave.data.SettingsRepository
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.json.JSONObject
import org.tensorflow.lite.Interpreter
import org.tensorflow.lite.flex.FlexDelegate
import java.io.File
import java.net.HttpURLConnection
import java.net.URL
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.util.Calendar
import java.util.concurrent.TimeUnit

/**
 * WorkManager CoroutineWorker that runs one federated-learning round per day.
 *
 * Constraints: NetworkType.CONNECTED + BatteryNotLow (WorkManager) plus
 * a custom battery > 80% OR charging.
 *
 * Each round:
 *   Checks the server for a newer global model; downloads it if available.
 *   Loads feedback-labelled stress readings from Room.
 *   Fine-tunes the local TFLite model using the `train` signature.
 *   Uploads the updated parameter tensors to the server for FedAvg aggregation.
 *   Marks readings as synced only after local training and upload finish cleanly.
 *
 * Raw biometric data stays on-device; only updated model parameter tensors leave the phone.
 */
class FLTrainingWorker(
    context: Context,
    params: WorkerParameters,
) : CoroutineWorker(context, params) {

    companion object {
        private const val TAG  = "FLTrainingWorker"

        private const val PTAG = "MWProfiling"
        private const val PREFS_NAME = "fl_prefs"
        private const val KEY_LOCAL_VERSION = "local_model_version"

        // Filename used for the downloaded / fine-tuned model in filesDir
        const val LOCAL_MODEL_FILENAME = "mindwave_fl_model.tflite"

        // Trainable model bundled in assets (fallback if no download yet)
        private const val BASE_TRAINABLE_ASSET = "mindwave_stress_trainable.tflite"

        // Minimum feedback samples required before running a training round.
        private const val MIN_FEEDBACK_SAMPLES = 3

        // Used to avoid using a corrupt file
        private const val MIN_WEIGHTS_FILE_BYTES = 100L

        /** On-device fine-tuning epochs per FL round. */
        private const val LOCAL_EPOCHS = 2

        /** Mini-batch size for the TFLite `train` signature call. */
        private const val BATCH_SIZE = 8

        private const val WORK_NAME = "fl_daily_training"

        // Used to bypass checks, for benchmarking.
        const val KEY_FORCE_START = "force_start"

        /**
         * Enqueues a unique periodic work request that fires daily at 2 AM.
         */
        fun enqueue(context: Context) {
            val constraints = Constraints.Builder()
                .setRequiredNetworkType(NetworkType.CONNECTED)
                .setRequiresBatteryNotLow(true)
                .build()

            val request = PeriodicWorkRequestBuilder<FLTrainingWorker>(1, TimeUnit.DAYS)
                .setConstraints(constraints)
                .setInitialDelay(delayUntilNext2AM(), TimeUnit.MILLISECONDS)
                .build()

            WorkManager.getInstance(context).enqueueUniquePeriodicWork(
                WORK_NAME,
                ExistingPeriodicWorkPolicy.KEEP,
                request,
            )
            Log.i(TAG, "FL training worker enqueued (initial delay ${delayUntilNext2AM() / 60_000} min)")
        }

        private fun delayUntilNext2AM(): Long {
            val now = Calendar.getInstance()
            val target = Calendar.getInstance().apply {
                set(Calendar.HOUR_OF_DAY, 2)
                set(Calendar.MINUTE, 0)
                set(Calendar.SECOND, 0)
                set(Calendar.MILLISECOND, 0)
                if (!after(now)) add(Calendar.DAY_OF_YEAR, 1)
            }
            return target.timeInMillis - now.timeInMillis
        }

        /**
         * Enqueues a one-time FL round that runs immediately, bypassing the battery gate
         * and the minimum-feedback-sample requirement.
         *
         * If the device has fewer than [MIN_FEEDBACK_SAMPLES] real feedback samples,
         * synthetic samples generated by the SyntheticWindowFactory are used.
         *
         * Call from the benchmark / developer UI to test FL without waiting for real data.
         */
        fun enqueueForce(context: Context) {
            val data = androidx.work.Data.Builder()
                .putBoolean(KEY_FORCE_START, true)
                .build()
            val request = androidx.work.OneTimeWorkRequestBuilder<FLTrainingWorker>()
                .setInputData(data)
                .build()
            WorkManager.getInstance(context).enqueue(request)
            Log.i(TAG, "FL force-start enqueued (one-time, no battery / sample-count gate)")
        }
    }

    override suspend fun doWork(): Result = withContext(Dispatchers.IO) {
        val forceStart = inputData.getBoolean(KEY_FORCE_START, false)
        val authRepo = AuthRepository(applicationContext)

        // offline, no network so no participation
        if (authRepo.isOfflineUser()) {
            Log.i(TAG, "Offline mode, skipping FL round")
            return@withContext Result.success()
        }

        // Respect user's FL opt-in setting
        val settingsRepo = SettingsRepository(applicationContext, authRepo.getEmail() ?: "")
        if (!settingsRepo.current().flEnabled) {
            Log.i(TAG, "FL disabled in settings, skipping")
            return@withContext Result.success()
        }

        // Gate on battery
        if (!forceStart && !isBatteryAbove80()) {
            Log.i(TAG, "Battery < 80% and not charging, skipping FL round")
            return@withContext Result.success()
        }
        if (forceStart) Log.i(TAG, "FL force-start: battery gate bypassed")

        // refresh jwt
        authRepo.ensureValidToken()
        val token: String? = authRepo.getToken()

        if (token == null) {
            if (forceStart) {
                Log.w(TAG, "No auth token, force-start will run local training only (no upload)")
            } else {
                Log.w(TAG, "No auth token (refresh failed or session expired), skipping FL round. " +
                    "Open the app and log in again to restore network FL.")
                return@withContext Result.success()
            }
        }

        val db = MindWaveDatabase.getInstance(applicationContext)

        // Check for a newer global model and download it
        if (token != null) {
            try {
                checkAndDownloadModel(token)
            } catch (e: Exception) {
                Log.w(TAG, "Model download failed (non-fatal): ${e.message}")
            }
        } else {
            Log.i(TAG, "Skipping model download, no auth token")
        }

        // Load feedback-labelled readings
        val readings = db.stressDao().getUnsyncedWithFeedback(authRepo.getEmail() ?: "")
        val scaler = com.example.mindwave.inference.ScalerNormalizer.fromAssets(applicationContext)
        if (scaler == null) {
            Log.w(TAG, "Scaler unavailable, skipping FL training to avoid raw/normalized mismatch")
            return@withContext Result.success()
        }

        // Pair each reading with its binary feedback label.
        // mood 1-2 means stress, mood 4-5 means calmness
        var labelledSamples = readings.mapNotNull { reading ->
            val tensor = reading.featureTensor ?: return@mapNotNull null
            val mood = db.journalDao().getFeedbackMood(reading.id) ?: return@mapNotNull null
            val label = when (mood) {
                1, 2 -> 1L
                4, 5 -> 0L
                else -> return@mapNotNull null
            }
            val raw = bytesToFloatArray(tensor)
            val expectedSize = com.example.mindwave.inference.FeatureExtractor.N_SUBWINDOWS *
                com.example.mindwave.inference.FeatureExtractor.N_FEATURES
            if (raw.size != expectedSize) {
                Log.w(TAG, "Skipping reading ${reading.id}: tensor has ${raw.size} floats, expected $expectedSize")
                return@mapNotNull null
            }
            floatArrayToBytes(scaler.normalize(raw)) to label
        }

        // If force-started and we don't have enough real samples, generate synthetic ones
        if (labelledSamples.size < MIN_FEEDBACK_SAMPLES) {
            if (forceStart) {
                Log.i(TAG, "Force-start: only ${labelledSamples.size} real samples, " +
                    "padding with synthetic windows from SyntheticWindowFactory")
                val scaler = com.example.mindwave.inference.ScalerNormalizer.fromAssets(applicationContext)
                val syntheticSamples = com.example.mindwave.inference.SyntheticWindowFactory
                    .generate(count = 20, stressFraction = 0.5f)
                    .mapNotNull { window ->
                        val raw = com.example.mindwave.inference.FeatureExtractor.extract(
                            hrValues   = window.hrValues,
                            tempValues = window.tempValues,
                            edaValues  = window.edaValues,
                            accX       = window.accXValues,
                            accY       = window.accYValues,
                            accZ       = window.accZValues,
                        ) ?: return@mapNotNull null
                        val normalized = scaler?.normalize(raw) ?: raw
                        val buf = java.nio.ByteBuffer.allocate(normalized.size * 4)
                            .order(java.nio.ByteOrder.LITTLE_ENDIAN)
                        normalized.forEach { buf.putFloat(it) }
                        val label = if (window.timestamp % 2 == 0L) 1L else 0L
                        buf.array() to label
                    }
                labelledSamples = labelledSamples + syntheticSamples
                Log.i(TAG, "Using ${labelledSamples.size} samples (${syntheticSamples.size} synthetic)")
            } else {
                Log.i(TAG, "Only ${labelledSamples.size} feedback sample(s), need $MIN_FEEDBACK_SAMPLES — skipping training")
                return@withContext Result.success()
            }
        }

        if (labelledSamples.isEmpty()) {
            Log.i(TAG, "No labelled samples with feature tensors — skipping training")
            return@withContext Result.success()
        }

        // Fine-tune the local model on feedback data
        val trainingUploaded = runLocalTraining(labelledSamples, token, labelledSamples.size)
        if (!trainingUploaded) {
            Log.w(TAG, "FL round did not complete cleanly - keeping readings unsynced for retry")
            return@withContext if (forceStart) Result.success() else Result.retry()
        }

        // Mark readings as synced and free the BLOB storage only after training + upload succeed.
        val ids = readings.map { it.id }
        if (ids.isNotEmpty() && token != null) {
            db.stressDao().markSynced(ids)
            db.stressDao().clearFeatureTensors(ids)
        }

        Result.success()
    }

    // Battery helpers
    private fun isBatteryAbove80(): Boolean {
        val filter = IntentFilter(Intent.ACTION_BATTERY_CHANGED)
        val intent = applicationContext.registerReceiver(null, filter) ?: return true
        val level  = intent.getIntExtra(BatteryManager.EXTRA_LEVEL, -1)
        val scale  = intent.getIntExtra(BatteryManager.EXTRA_SCALE, 100)
        val status = intent.getIntExtra(BatteryManager.EXTRA_STATUS, -1)
        val isCharging = status == BatteryManager.BATTERY_STATUS_CHARGING
                || status == BatteryManager.BATTERY_STATUS_FULL
        return isCharging || (level >= 0 && (level.toFloat() / scale) >= 0.80f)
    }

    // Model update
    private fun checkAndDownloadModel(token: String) {
        val prefs = applicationContext.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        val localVersion = prefs.getInt(KEY_LOCAL_VERSION, 0)

        val body = httpGet("${AuthRepository.BASE_URL}/model/latest", token) ?: return
        val json = JSONObject(body)
        val serverVersion = json.optInt("version", 0)
        val weightsPath   = json.optString("weights_path", "")

        if (serverVersion <= localVersion) {
            Log.d(TAG, "Model is up to date (v$localVersion)")
            return
        }

        Log.i(TAG, "Downloading global model v$serverVersion (was v$localVersion)")
        val modelBytes = httpGetBytes(
            "${AuthRepository.BASE_URL}/model/$serverVersion/download", token
        ) ?: return

        if (weightsPath.endsWith(".npz")) {
            // Server sent weights
            val npzFile = File(applicationContext.filesDir, "fl_global_weights.npz")
            npzFile.writeBytes(modelBytes)
            Log.i(TAG, "Global weights .npz staged for restore (${modelBytes.size} bytes)")
        } else {
            // Server sent a full .tflite, replace local model
            val dest = File(applicationContext.filesDir, LOCAL_MODEL_FILENAME)
            dest.writeBytes(modelBytes)
            Log.i(TAG, "Global model v$serverVersion saved (${modelBytes.size} bytes)")
        }

        prefs.edit().putInt(KEY_LOCAL_VERSION, serverVersion).apply()
    }

    // Local training
    private fun runLocalTraining(samples: List<Pair<ByteArray, Long>>, token: String?, sampleCount: Int): Boolean {
        val t0 = SystemClock.elapsedRealtimeNanos()
        val localFile    = File(applicationContext.filesDir, LOCAL_MODEL_FILENAME)
        val flexDelegate = FlexDelegate()

        Trace.beginSection("MW.fl.load")
        val interp = try {
            val opts = Interpreter.Options().apply {
                numThreads = 2
                addDelegate(flexDelegate)
            }
            if (localFile.exists()) {
                Log.d(TAG, "Loading fine-tune model from filesDir: ${localFile.name}")
                Interpreter(localFile, opts)
            } else {
                Log.d(TAG, "Loading fine-tune model from assets ($BASE_TRAINABLE_ASSET)")
                val fd  = applicationContext.assets.openFd(BASE_TRAINABLE_ASSET)
                val buf = java.io.FileInputStream(fd.fileDescriptor).channel
                    .map(java.nio.channels.FileChannel.MapMode.READ_ONLY, fd.startOffset, fd.declaredLength)
                Interpreter(buf, opts)
            }
        } catch (e: Exception) {
            Trace.endSection()
            Log.e(TAG, "Cannot load trainable model: ${e.message}")
            flexDelegate.close()
            return false
        }
        Trace.endSection()
        val tLoad = SystemClock.elapsedRealtimeNanos()
        Log.i(PTAG, "fl.load = ${(tLoad - t0) / 1_000}µs")
        return try {
            val nSteps    = com.example.mindwave.inference.FeatureExtractor.N_SUBWINDOWS
            val nFeatures = com.example.mindwave.inference.FeatureExtractor.N_FEATURES

            /* Here we determine whether to restore weights from a previously downloaded .npz,
            from a local fl_weights.bin, or from the initial bundled weights. */

            val globalNpz    = File(applicationContext.filesDir, "fl_global_weights.npz")
            val weightsFile  = File(applicationContext.filesDir, "fl_weights.bin")
            var variablesInitialized = false

            Trace.beginSection("MW.fl.restore")
            when {
                globalNpz.exists() -> {
                    restoreWeightsNpz(interp, globalNpz)
                    globalNpz.delete()
                    Log.i(TAG, "Restored global aggregated weights from .npz")
                    variablesInitialized = true
                }
                weightsFile.exists() && weightsFile.length() > MIN_WEIGHTS_FILE_BYTES -> {
                    val restored = restoreWeights(interp, weightsFile)
                    if (restored) {
                        Log.i(TAG, "Restored local weights from fl_weights.bin")
                        variablesInitialized = true
                    }
                }
            }
            if (!variablesInitialized) {
                Log.i(TAG, "First FL run: restoring initial weights from assets")
                val restored = restoreWeightsFromAssets(interp, "initial_weights.bin")
                if (restored) {
                    variablesInitialized = true
                } else {
                    Log.w(TAG, "Could not restore from assets, skipping variable init")
                }
            }
            Trace.endSection()
            val tRestore = SystemClock.elapsedRealtimeNanos()
            Log.i(PTAG, "fl.restore = ${(tRestore - tLoad) / 1_000}µs")

            var trainSucceeded = false
            Trace.beginSection("MW.fl.train")
            try {
                repeat(LOCAL_EPOCHS) { epoch ->
                    var batchLoss  = 0.0
                    var batchCount = 0

                    samples.chunked(BATCH_SIZE).forEach { batch ->
                        val bsz = batch.size

                        val xArr = Array(bsz) { b ->
                            val src = ByteBuffer.wrap(batch[b].first).order(ByteOrder.LITTLE_ENDIAN)
                            Array(nSteps) { FloatArray(nFeatures) { src.float } }
                        }
                        val yArr    = LongArray(bsz) { b -> batch[b].second }
                        val lossOut = FloatArray(1)

                        interp.runSignature(
                            mapOf("x" to xArr, "y" to yArr),
                            mutableMapOf<String, Any>("loss" to lossOut),
                            "train",
                        )
                        batchLoss += lossOut[0]
                        batchCount++
                    }

                    Log.d(TAG, "Epoch ${epoch + 1}/$LOCAL_EPOCHS — avg loss ${"%.4f".format(
                        if (batchCount > 0) batchLoss / batchCount else 0.0)}")
                }
                trainSucceeded = true
                Log.i(TAG, "On-device training completed successfully")
            } catch (e: Exception) {
                Log.w(TAG, "TFLite train signature failed: ${e.message}")
                Log.w(TAG, "FL round continues without gradient update — weights unchanged")
            }
            Trace.endSection()
            val tTrain = SystemClock.elapsedRealtimeNanos()
            Log.i(PTAG, "fl.train = ${(tTrain - tRestore) / 1_000}µs  succeeded=$trainSucceeded  samples=${samples.size}  epochs=$LOCAL_EPOCHS")

            // Persist updated weights
            Trace.beginSection("MW.fl.save")
            val savedWeights = saveWeights(interp, weightsFile)
            Trace.endSection()
            val tSave = SystemClock.elapsedRealtimeNanos()
            Log.i(PTAG, "fl.save = ${(tSave - tTrain) / 1_000}µs  file=${weightsFile.length()}B")
            if (!trainSucceeded || !savedWeights) {
                Log.w(TAG, "Skipping upload because local training or weight saving failed")
                return false
            }

            // Upload updated parameter tensors to server
            Trace.beginSection("MW.fl.upload")
            var uploadOk = false
            if (token != null) {
                val baseModelVersion = applicationContext
                    .getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
                    .getInt(KEY_LOCAL_VERSION, 0)
                uploadOk = httpPostBytes(
                    "${AuthRepository.BASE_URL}/model/fl/submit-weights",
                    token,
                    weightsFile.readBytes(),
                    sampleCount,
                    baseModelVersion,
                )
                if (uploadOk) Log.i(TAG, "Weights uploaded for aggregation")
                else          Log.w(TAG, "Weight upload failed (will retry next round)")
            } else {
                Log.i(TAG, "No auth token - local weights saved but not uploaded to server")
            }
            Trace.endSection()
            val tUpload = SystemClock.elapsedRealtimeNanos()
            Log.i(PTAG, "fl.upload = ${(tUpload - tSave) / 1_000}µs")
            Log.i(PTAG, "fl.total  = ${(tUpload - t0) / 1_000}µs  (load+restore+train+save+upload)")

            com.example.mindwave.inference.StressInferenceRepository.reloadModel()

            token == null || uploadOk
        } catch (e: Exception) {
            Log.e(TAG, "Local training failed: ${e.message}")
            false
        } finally {
            interp.close()
            flexDelegate.close()
        }
    }

    // weight persistance helpers

    /**
     * Extracts all weight tensors via the `parameters` signature and writes them to [dest].
     */
    private fun bytesToFloatArray(bytes: ByteArray): FloatArray {
        val buf = ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN)
        return FloatArray(bytes.size / 4) { buf.float }
    }

    private fun floatArrayToBytes(values: FloatArray): ByteArray {
        val buf = ByteBuffer.allocate(values.size * 4).order(ByteOrder.LITTLE_ENDIAN)
        values.forEach { buf.putFloat(it) }
        return buf.array()
    }

    private fun saveWeights(interp: Interpreter, dest: File): Boolean {
        return try {
            val outputs = mutableMapOf<String, Any>()
            interp.runSignature(
                emptyMap<String, Any>(),
                outputs,
                "parameters",
            )

            java.io.DataOutputStream(dest.outputStream().buffered()).use { dos ->
                dos.writeInt(outputs.size)
                outputs.entries.sortedBy { it.key }.forEach { (_, v) ->
                    val arr: FloatArray = when (v) {
                        is FloatArray -> v
                        is Array<*>   -> {
                            val flat = mutableListOf<Float>()
                            fun flatten(obj: Any?) {
                                when (obj) {
                                    is Array<*>   -> obj.forEach { flatten(it) }
                                    is FloatArray -> obj.forEach { flat.add(it) }
                                    is Float      -> flat.add(obj)
                                }
                            }
                            flatten(v)
                            flat.toFloatArray()
                        }
                        else -> FloatArray(0)
                    }
                    dos.writeInt(arr.size)
                    arr.forEach { dos.writeFloat(it) }
                }
            }
            Log.d(TAG, "Saved ${outputs.size} weight tensor(s) to ${dest.name}")
            true
        } catch (e: Exception) {
            Log.w(TAG, "saveWeights failed: ${e.message}")
            false
        }
    }

    /**
     * Reads weight tensors written by [saveWeights] and loads them via the `restore` signature.
     */
    private fun restoreWeights(interp: Interpreter, src: File): Boolean {
        return try {
            java.io.DataInputStream(src.inputStream().buffered()).use { dis ->
                val count = dis.readInt()
                if (count !in 1..100) {
                    Log.w(TAG, "restoreWeights: corrupt file ${src.name} (count=$count) — deleting")
                    src.delete()
                    return false
                }
                val inputs = (0 until count).associate { i ->
                    val size = dis.readInt()
                    if (size !in 1..10_000_000) {
                        Log.w(TAG, "restoreWeights: corrupt tensor $i size=$size — deleting")
                        src.delete()
                        return false
                    }
                    "vals_$i" to FloatArray(size) { dis.readFloat() }
                }
                interp.runSignature(inputs, mutableMapOf(), "restore")
            }
            Log.d(TAG, "Restored weights from ${src.name}")
            true
        } catch (e: Exception) {
            Log.w(TAG, "restoreWeights failed: ${e.message}")
            src.delete()   // remove corrupt file so next run starts clean
            false
        }
    }

    /**
     * Restores initial weights from a bundled asset file (same format as [saveWeights]).
     * Called on the very first FL round before any local fl_weights.bin exists.
     */
    private fun restoreWeightsFromAssets(interp: Interpreter, assetName: String): Boolean {
        return try {
            applicationContext.assets.open(assetName).buffered().use { stream ->
                java.io.DataInputStream(stream).use { dis ->
                    val count = dis.readInt()
                    if (count !in 1..100) {
                        Log.w(TAG, "restoreWeightsFromAssets: corrupt asset $assetName (count=$count)")
                        return false
                    }
                    val inputs = (0 until count).associate { i ->
                        val size = dis.readInt()
                        if (size !in 1..10_000_000) {
                            Log.w(TAG, "restoreWeightsFromAssets: corrupt tensor $i size=$size")
                            return false
                        }
                        "vals_$i" to FloatArray(size) { dis.readFloat() }
                    }
                    interp.runSignature(inputs, mutableMapOf(), "restore")
                }
            }
            Log.d(TAG, "Restored initial weights from asset: $assetName")
            true
        } catch (e: Exception) {
            Log.w(TAG, "restoreWeightsFromAssets failed: ${e.message}")
            false
        }
    }

    /**
     * Reads a server-produced .npz file and loads tensors via the `restore` signature.
     */
    private fun restoreWeightsNpz(interp: Interpreter, src: File): Boolean {
        return try {
            val inputs = mutableMapOf<String, Any>()
            java.util.zip.ZipFile(src).use { zip ->
                zip.entries().asSequence().sortedBy { it.name }.forEachIndexed { i, entry ->
                    zip.getInputStream(entry).use { stream ->
                        val bytes = stream.readBytes()
                        // NPY header: magic(6) + major(1) + minor(1) + headerLen(2-LE) + header
                        val headerLen  = (bytes[9].toInt() and 0xFF shl 8) or (bytes[8].toInt() and 0xFF)
                        val dataOffset = 10 + headerLen
                        val buf = ByteBuffer.wrap(bytes, dataOffset, bytes.size - dataOffset)
                            .order(ByteOrder.LITTLE_ENDIAN)
                        val floats = FloatArray((bytes.size - dataOffset) / 4) { buf.float }
                        inputs["vals_$i"] = floats
                    }
                }
            }
            interp.runSignature(inputs, mutableMapOf(), "restore")
            Log.d(TAG, "Restored ${inputs.size} weight tensor(s) from npz")
            true
        } catch (e: Exception) {
            Log.w(TAG, "restoreWeightsNpz failed: ${e.message}")
            false
        }
    }

    // HTTP helpers
    private fun httpGet(urlStr: String, token: String): String? = try {
        (URL(urlStr).openConnection() as HttpURLConnection).run {
            requestMethod = "GET"
            setRequestProperty("Authorization", "Bearer $token")
            connectTimeout = 10_000
            readTimeout = 15_000
            connect()
            if (responseCode == HttpURLConnection.HTTP_OK) {
                inputStream.bufferedReader().readText()
            } else {
                Log.w(TAG, "GET $urlStr → HTTP $responseCode")
                null
            }
        }
    } catch (e: Exception) {
        Log.w(TAG, "GET $urlStr: ${e.message}")
        null
    }

    private fun httpGetBytes(urlStr: String, token: String): ByteArray? = try {
        (URL(urlStr).openConnection() as HttpURLConnection).run {
            requestMethod = "GET"
            setRequestProperty("Authorization", "Bearer $token")
            connectTimeout = 10_000
            readTimeout = 120_000   // model download may be tens of MBs
            connect()
            if (responseCode == HttpURLConnection.HTTP_OK) {
                inputStream.readBytes()
            } else {
                Log.w(TAG, "GET bytes $urlStr → HTTP $responseCode")
                null
            }
        }
    } catch (e: Exception) {
        Log.w(TAG, "GET bytes $urlStr: ${e.message}")
        null
    }

    /**
     * POST [body] as multipart/form-data with field name "weights_file" to [urlStr].
     * Returns true on HTTP 202 (Accepted), false on any failure.
     */
    private fun httpPostBytes(urlStr: String, token: String, body: ByteArray, sampleCount: Int, baseModelVersion: Int): Boolean = try {
        val boundary = "----MindWaveFL${System.currentTimeMillis()}"
        (URL(urlStr).openConnection() as HttpURLConnection).run {
            requestMethod = "POST"
            setRequestProperty("Authorization", "Bearer $token")
            setRequestProperty("Content-Type", "multipart/form-data; boundary=$boundary")
            connectTimeout = 15_000
            readTimeout = 60_000
            doOutput = true

            outputStream.bufferedWriter(Charsets.UTF_8).use { writer ->
                fun writeField(name: String, value: String) {
                    writer.write("--$boundary\r\n")
                    writer.write("Content-Disposition: form-data; name=\"$name\"\r\n\r\n")
                    writer.write(value)
                    writer.write("\r\n")
                }
                writeField("sample_count", sampleCount.toString())
                writeField("base_model_version", baseModelVersion.toString())

                writer.write("--$boundary\r\n")
                writer.write("Content-Disposition: form-data; name=\"weights_file\"; filename=\"fl_weights.bin\"\r\n")
                writer.write("Content-Type: application/octet-stream\r\n\r\n")
                writer.flush()
                outputStream.write(body)
                outputStream.flush()
                writer.write("\r\n--$boundary--\r\n")
                writer.flush()
            }

            val code = responseCode
            Log.d(TAG, "POST weights $urlStr → HTTP $code")
            code == HttpURLConnection.HTTP_ACCEPTED   // 202
        }
    } catch (e: Exception) {
        Log.w(TAG, "POST bytes $urlStr: ${e.message}")
        false
    }
}
