package com.example.mindwave.inference

import android.content.Context
import android.os.Trace
import android.util.Log
import com.example.mindwave.data.AuthRepository
import com.example.mindwave.data.LatencyRecord
import com.example.mindwave.data.MindWaveDatabase
import com.example.mindwave.data.StressReading
import com.example.mindwave.data.XaiExplanation
import com.example.mindwave.sync.MobileDataListenerService
import java.util.concurrent.atomic.AtomicInteger
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.launch
import org.tensorflow.lite.Interpreter
import org.tensorflow.lite.flex.FlexDelegate
import java.io.File
import java.io.FileInputStream
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.channels.FileChannel

/**
 * Wires MobileDataListenerService sensor windows to TFLite inference and Room persistence.
 *
 * Pipeline:
 *   SensorWindow => FeatureExtractor => ScalerNormalizer => TFLite  => StressReading (Room) +
 *   XaiExplanation rows (Room) => DashboardViewModel observes via Flow => UI
 *
 * Model loading priority:
 *   FL-updated local file (filesDir/mindwave_fl_model.tflite)
 *   Trainable asset (mindwave_stress_trainable.tflite)
 *   Plain inference asset (mindwave_stress.tflite)
 *
 * Inference signature priority:
 *   "infer"  (trainable model) — input "x", output "logits"
 *   "serving_default" (plain model) — input "features", output "output_0"
 *   interp.run() raw ByteBuffer fallback — universal last resort
 */
class StressInferenceRepository private constructor(private val context: Context) {

    companion object {
        private const val TAG = "MWInference"
        private const val TRAINABLE_ASSET = "mindwave_stress_trainable.tflite"
        private const val PLAIN_ASSET = "mindwave_stress.tflite"

        @Volatile
        private var instance: StressInferenceRepository? = null

        fun init(context: Context): StressInferenceRepository {
            return instance ?: synchronized(this) {
                instance ?: StressInferenceRepository(context.applicationContext)
                    .also {
                        instance = it
                        it.register()
                    }
            }
        }

        /** Call after FLTrainingWorker saves a new global model to filesDir. */
        fun reloadModel() {
            instance?.register()
        }

        /**
         * Injects a synthetic SensorWindow as if it arrived from the watch.
         * Use from the emulator / developer menu to verify the full inference pipeline.
         *
         * HR:   60 samples @ ~1 Hz, ~75 BPM +/- small noise
         * EDA:  240 samples @ ~4 Hz, ~20 microS
         * TEMP: 6 samples  @ ~0.1 Hz, 32.5 degrees
         * ACC:  1500 samples @ ~25 Hz, light motion
         */
        fun simulateWatchWindow() {
            val inst = instance ?: run {
                Log.w(TAG, "simulateWatchWindow: repository not initialised yet")
                return
            }
            val now = System.currentTimeMillis()
            val hrCount = 60
            val edaCount = 240
            val accCount = 1500
            val tmpCount = 6

            val window = MobileDataListenerService.SensorWindow(
                timestamp = now,
                hrTimes = LongArray(hrCount) { now - (hrCount - it) * 1_000L },
                hrValues = FloatArray(hrCount) { 75f + (it % 7 - 3).toFloat() },
                tempTimes = LongArray(tmpCount) { now - (tmpCount - it) * 10_000L },
                tempValues = FloatArray(tmpCount) { 32.5f + it * 0.05f },
                edaTimes = LongArray(edaCount) { now - (edaCount - it) * 250L },
                edaValues = FloatArray(edaCount) { 20f + (it % 12) * 0.5f },
                accXValues = FloatArray(accCount) { 0.05f * kotlin.math.sin(it * 0.1).toFloat() },
                accYValues = FloatArray(accCount) { 0.03f * kotlin.math.cos(it * 0.1).toFloat() },
                accZValues = FloatArray(accCount) { 9.81f + 0.02f * (it % 5 - 2) },
                mood = 0,
            )
            Log.i(
                TAG,
                "▶ Simulated watch window injected (HR=${hrCount}smp, EDA=${edaCount}smp, ACC=${accCount}smp)"
            )
            inst.scope.launch { inst.processWindow(window) }
        }

        /**
         * Injects [count] synthetic windows generated by [SyntheticWindowFactory] into the
         * full inference pipeline (same path as a real watch window). Used for benchmarking
         */
        fun runBenchmark(count: Int = 110, stressFraction: Float = 0.5f) {
            val inst = instance ?: run {
                Log.w(TAG, "runBenchmark: repository not initialised yet")
                return
            }
            // Reset the warm-up counter so we get exactly WARMUP_COUNT warm-up windows
            inst.windowCounter.set(0)
            val windows = SyntheticWindowFactory.generate(count, stressFraction)
            Log.i(
                TAG,
                "▶ Benchmark starting: $count windows (first ${LatencyRecord.WARMUP_COUNT} are warm-up)"
            )
            inst.scope.launch {
                windows.forEachIndexed { i, window ->
                    inst.processWindow(window)
                    if ((i + 1) % 10 == 0) Log.i(TAG, "Benchmark progress: ${i + 1}/$count")
                }
                Log.i(TAG, "▶ Benchmark complete — check BenchmarkScreen for statistics")
            }
        }
    }

    private val scope = CoroutineScope(SupervisorJob() + Dispatchers.Default)
    private val db = MindWaveDatabase.getInstance(context)
    private val authRepo = AuthRepository(context)
    private val contextCorrelator = com.example.mindwave.data.ContextCorrelator(context)
    private val scaler = ScalerNormalizer.fromAssets(context)

    /** Counts total windows processed since process start */
    private val windowCounter = AtomicInteger(0)

    @Volatile
    private var interpreter: Interpreter? = null
    @Volatile
    private var flexDelegate: FlexDelegate? = null

    // model loading

    /**
     * Loads the best available TFLite model and subscribes to sensor windows.
     */
    private fun register() {
        val newFlex = FlexDelegate()
        val flexOpts = Interpreter.Options().apply { numThreads = 2; addDelegate(newFlex) }
        val plainOpts = Interpreter.Options().apply { numThreads = 2 }

        var newInterp: Interpreter? = null
        var usingFlex = false

        // local FL-updated model.
        val localFile =
            File(context.filesDir, com.example.mindwave.fl.FLTrainingWorker.LOCAL_MODEL_FILENAME)
        if (localFile.exists()) {
            try {
                val candidate = Interpreter(localFile, flexOpts)
                if (smokeTestInterpreter(candidate)) {
                    newInterp = candidate
                    usingFlex = true
                    Log.i(TAG, "Loaded FL-updated model from filesDir: ${localFile.name} ✓")
                } else {
                    candidate.close()
                    Log.w(TAG, "FL-updated model smoke-test failed — discarding")
                }
            } catch (e: Exception) {
                Log.w(TAG, "FL-updated model load failed (${e.message}) — trying assets")
            }
        }

        // Trainable asset
        if (newInterp == null) {
            try {
                val fd = context.assets.openFd(TRAINABLE_ASSET)
                val buf = FileInputStream(fd.fileDescriptor).channel
                    .map(FileChannel.MapMode.READ_ONLY, fd.startOffset, fd.declaredLength)
                val candidate = Interpreter(buf, flexOpts)
                if (smokeTestInterpreter(candidate)) {
                    newInterp = candidate
                    usingFlex = true
                    Log.i(TAG, "Loaded trainable model from assets: $TRAINABLE_ASSET ✓")
                } else {
                    candidate.close()
                    Log.w(
                        TAG,
                        "Trainable model smoke-test failed (Flex ops unavailable on this ABI) — falling back to plain model"
                    )
                }
            } catch (e: Exception) {
                Log.w(
                    TAG,
                    "Trainable asset unavailable (${e.javaClass.simpleName}: ${e.message}) — falling back to plain model"
                )
            }
        }

        // Inference-only model
        if (newInterp == null) {
            try {
                val fd = context.assets.openFd(PLAIN_ASSET)
                val buf = FileInputStream(fd.fileDescriptor).channel
                    .map(FileChannel.MapMode.READ_ONLY, fd.startOffset, fd.declaredLength)
                newInterp = Interpreter(buf, plainOpts)
                Log.i(TAG, "Loaded plain model from assets: $PLAIN_ASSET ✓")
            } catch (e: Exception) {
                Log.e(TAG, "All model load attempts failed: ${e.message}")
            }
        }

        // Swap interpreters
        val oldInterp = interpreter
        val oldFlex = flexDelegate
        interpreter = newInterp
        flexDelegate = if (usingFlex) newFlex else null.also { newFlex.close() }
        oldInterp?.close()
        oldFlex?.close()

        // Subscribe to live windows from the watch
        MobileDataListenerService.onWindowReceived = { window ->
            scope.launch { processWindow(window) }
        }
        Log.i(
            TAG,
            "StressInferenceRepository registered — interpreter=${if (newInterp != null) "ready" else "NULL"}"
        )
    }

    /**
     * Used to verify the interpeter is functional after loading. Without calling this
     * function before-hand, the TFLite trainable would be initialized only with zeros,
     * therefore any inference call would crash.
     *
     * We use initial weights to seed the ResourceVariables, so the model can produce
     * valid results.
     */
    private fun smokeTestInterpreter(interp: Interpreter): Boolean {
        return try {
            // Seed resource variables from the bundled initial weights asset
            try {
                context.assets.open("initial_weights.bin").buffered().use { stream ->
                    java.io.DataInputStream(stream).use { dis ->
                        val count = dis.readInt()
                        if (count in 1..100) {
                            val inputs = (0 until count).associate { i ->
                                val size = dis.readInt()
                                "vals_$i" to FloatArray(size) { dis.readFloat() }
                            }
                            interp.runSignature(inputs, mutableMapOf(), "restore")
                        }
                    }
                }
            } catch (_: Exception) {
                // skip, corruption or asset missing
            }

            val dummy =
                FloatArray(FeatureExtractor.N_SUBWINDOWS * FeatureExtractor.N_FEATURES) { 0f }
            runInference(interp, dummy) != null
        } catch (_: Exception) {
            false
        }
    }

    // processing pipeline

    private suspend fun processWindow(window: MobileDataListenerService.SensorWindow) {
        val timer = PipelineTimer(windowId = window.timestamp)
        val isWarmup = windowCounter.getAndIncrement() < LatencyRecord.WARMUP_COUNT

        // Window incoming
        timer.receivedNs = timer.now()

        // extract features
        Trace.beginSection("MW.features")
        val rawFeatures = FeatureExtractor.extract(
            hrValues = window.hrValues,
            tempValues = window.tempValues,
            edaValues = window.edaValues,
            accX = window.accXValues,
            accY = window.accYValues,
            accZ = window.accZValues,
        )
        Trace.endSection()
        if (rawFeatures == null) {
            Log.w(
                TAG,
                "Not enough sensor data to run inference (HR=${window.hrValues.size} samples)"
            )
            return
        }
        timer.featuresNs = timer.now()

        // apply training-time z-score standardisation
        Trace.beginSection("MW.normalize")
        val features = scaler?.normalize(rawFeatures) ?: rawFeatures
        Trace.endSection()
        timer.normalizedNs = timer.now()

        // run TFLite inference
        val interp = interpreter
        if (interp == null) {
            Log.w(TAG, "TFLite interpreter not ready — skipping inference")
            return
        }

        Trace.beginSection("MW.infer")
        val probs = runInference(interp, features)
        Trace.endSection()
        if (probs == null) return
        val stressScore = probs.indices.maxByOrNull { probs[it] } ?: 0
        timer.inferenceNs = timer.now()

        // Full-window RMSSD for logging
        val rmssdFull = if (window.hrValues.size >= 3) {
            val rr = window.hrValues.map { 60_000f / it.coerceAtLeast(1f) }
            val diffs = (1 until rr.size).map { kotlin.math.abs(rr[it] - rr[it - 1]) }
            kotlin.math.sqrt(diffs.map { it * it }.average()).toFloat()
        } else 0f

        Log.i(
            TAG,
            "Inference: normal=%.2f stress=%.2f → class=$stressScore | HR=${window.hrValues.size}smp RMSSD_window=${
                "%.1f".format(rmssdFull)
            }ms warmup=$isWarmup"
                .format(probs[0], probs[1])
        )

        // Run gradient-based XAI
        Trace.beginSection("MW.explain")
        val saliency = runExplain(interp, features)
        Trace.endSection()
        timer.xaiNs = timer.now()

        // Persist StressReading to Room
        val tempMeanWhole = if (window.tempValues.isNotEmpty())
            window.tempValues.average().toFloat() else rawFeatures.extractFeatureAt(14)

        val edaSclRaw = if (window.edaValues.isNotEmpty())
            window.edaValues.average().toFloat() else 0f

        Trace.beginSection("MW.room")
        val reading = StressReading(
            timestamp = window.timestamp,
            userEmail = authRepo.getEmail() ?: "",
            hrvMean = rawFeatures.extractFeatureAt(0),
            hrvSdnn = rawFeatures.extractFeatureAt(1),
            hrvRmssd = rmssdFull,
            edaScl = edaSclRaw,
            edaScr = rawFeatures.extractFeatureAt(9),
            tempMean = tempMeanWhole,
            accMag = rawFeatures.extractFeatureAt(19),
            stressScore = stressScore,
            stressProbBaseline = probs[0],
            stressProbStress = probs[1],
            stressProbAmusement = 0f,
            featureTensor = floatArrayToBytes(rawFeatures),
        )
        val readingId = db.stressDao().insert(reading)

        // Persist XAI rows
        if (saliency != null) {
            val featureNames = buildFeatureNames()
            val xaiRows = featureNames.mapIndexed { idx, name ->
                XaiExplanation(
                    readingId = readingId,
                    featureName = name,
                    importance = saliency.getOrElse(idx) { 0f },
                    rank = idx,
                )
            }.sortedByDescending { it.importance }
                .mapIndexed { rank, xai -> xai.copy(rank = rank) }
            db.xaiDao().insertAll(xaiRows)
        }
        Trace.endSection()
        timer.roomNs = timer.now()

        // Evaluate alert policy immediately.
        Trace.beginSection("MW.alert")
        com.example.mindwave.alert.StressAlertWorker.evaluateAndMaybeAlert(context)
        Trace.endSection()
        timer.alertNs = timer.now()

        // Persist latency record for profiling (µs precision)
        db.latencyDao().insert(
            LatencyRecord(
                windowId = timer.windowId,
                featureUs = timer.featureUs,
                normalizeUs = timer.normalizeUs,
                inferenceUs = timer.inferenceUs,
                xaiUs = timer.xaiUs,
                roomUs = timer.roomUs,
                alertUs = timer.alertUs,
                totalUs = timer.totalUs,
                isWarmup = isWarmup,
            )
        )
        Log.d(
            TAG, "Latency [warmup=$isWarmup] total=${timer.totalMs}ms | " +
                    "feat=${timer.featureUs}µs " +
                    "norm=${timer.normalizeUs}µs " +
                    "infer=${timer.inferenceUs}µs " +
                    "xai=${timer.xaiUs}µs " +
                    "room=${timer.roomUs}µs " +
                    "alert=${timer.alertUs}µs"
        )

        // Context enrichment (weather / calendar)
        contextCorrelator.correlate(reading.copy(id = readingId))

        // Push score to paired watch
        val percent = (probs[1] * 100).toInt()
        com.example.mindwave.sync.WatchStressSender.send(
            context = context,
            percent = percent,
            label = com.example.mindwave.ui.theme.stressLabel(percent),
            timestamp = window.timestamp,
            readingId = readingId,
        )
    }

    // tflite helpers
    /**
     * Build shape-[1, N_SUBWINDOWS, N_FEATURES] 3-D Java array from the flat feature vector.
     * TFLite's runSignature() requires typed Java arrays.
     */
    private fun featuresToInputArray(features: FloatArray): Array<Array<FloatArray>> {
        val sub = FeatureExtractor.N_SUBWINDOWS
        val nf = FeatureExtractor.N_FEATURES
        return Array(1) { Array(sub) { s -> FloatArray(nf) { f -> features[s * nf + f] } } }
    }

    /** ByteBuffer version, used only by the raw interp.run() last-resort fallback. */
    private fun featuresToBuffer(features: FloatArray): ByteBuffer {
        val buf = ByteBuffer.allocateDirect(
            FeatureExtractor.N_SUBWINDOWS * FeatureExtractor.N_FEATURES * 4
        ).order(ByteOrder.nativeOrder())
        features.forEach { buf.putFloat(it) }
        buf.rewind()
        return buf
    }

    /**
     * Run inference with three-tier fallback:
     *   runSignature("infer"), trainable model  (x produces logits)
     *   runSignature("serving_default"), plain model (features produce an output)
     *   interp.run(), raw ByteBuffer, works with any single-signature model
     */
    private fun runInference(interp: Interpreter, features: FloatArray): FloatArray? {
        return try {
            val inputArr = featuresToInputArray(features)
            val outputArr = Array(1) { FloatArray(2) }
            var ran = false

            if (!ran) {
                try {
                    interp.runSignature(
                        mapOf("x" to inputArr),
                        mutableMapOf<String, Any>("logits" to outputArr),
                        "infer",
                    )
                    ran = true
                    Log.d(TAG, "runSignature(infer) OK")
                } catch (e: Exception) {
                    Log.w(TAG, "infer signature failed: ${e.message}")
                }
            }

            if (!ran) {
                try {
                    interp.runSignature(
                        mapOf("features" to inputArr),
                        mutableMapOf<String, Any>("output_0" to outputArr),
                        "serving_default",
                    )
                    ran = true
                    Log.d(TAG, "runSignature(serving_default) OK")
                } catch (e: Exception) {
                    Log.w(TAG, "serving_default signature failed: ${e.message}")
                }
            }

            if (!ran) {
                try {
                    val inputBuf = featuresToBuffer(features)
                    val outputBuf = ByteBuffer.allocateDirect(2 * 4).order(ByteOrder.nativeOrder())
                    interp.run(inputBuf, outputBuf)
                    outputBuf.rewind()
                    outputArr[0][0] = outputBuf.float
                    outputArr[0][1] = outputBuf.float
                    ran = true
                    Log.d(TAG, "interp.run() raw fallback OK")
                } catch (e: Exception) {
                    Log.e(TAG, "interp.run() fallback also failed: ${e.message}")
                }
            }

            if (!ran) {
                Log.e(TAG, "No recognised inference path succeeded in model")
                return null
            }

            val raw = outputArr[0]
            val sum = raw.sum()
            if (sum < 0.99f || sum > 1.01f) softmax(raw) else raw
        } catch (e: Exception) {
            Log.e(TAG, "Inference failed: ${e.message}")
            null
        }
    }

    /** Raw inference without logging, used by the ablation XAI fallback.
     * The difference is that this function doesn't log errors, so it can be called for
     * testing ablation without spamming the log.
     * */
    private fun runInferenceRaw(interp: Interpreter, features: FloatArray): FloatArray? {
        return try {
            val inputArr = featuresToInputArray(features)
            val outputArr = Array(1) { FloatArray(2) }
            var ran = false
            try {
                interp.runSignature(
                    mapOf("x" to inputArr),
                    mutableMapOf<String, Any>("logits" to outputArr),
                    "infer"
                )
                ran = true
            } catch (_: Exception) {
            }
            if (!ran) {
                try {
                    interp.runSignature(
                        mapOf("features" to inputArr),
                        mutableMapOf<String, Any>("output_0" to outputArr),
                        "serving_default"
                    )
                    ran = true
                } catch (_: Exception) {
                }
            }
            if (!ran) {
                try {
                    val inputBuf = featuresToBuffer(features)
                    val outputBuf = ByteBuffer.allocateDirect(2 * 4).order(ByteOrder.nativeOrder())
                    interp.run(inputBuf, outputBuf)
                    outputBuf.rewind()
                    outputArr[0][0] = outputBuf.float
                    outputArr[0][1] = outputBuf.float
                    ran = true
                } catch (_: Exception) {
                }
            }
            if (!ran) return null
            val raw = outputArr[0]
            val sum = raw.sum()
            if (sum < 0.99f || sum > 1.01f) softmax(raw) else raw
        } catch (_: Exception) {
            null
        }
    }

    private fun softmax(logits: FloatArray): FloatArray {
        val max = logits.max()
        val exps =
            FloatArray(logits.size) { kotlin.math.exp((logits[it] - max).toDouble()).toFloat() }
        val sumExp = exps.sum()
        return FloatArray(logits.size) { exps[it] / sumExp }
    }

    /**
     * Run the "explain" signature (gradient-based XAI).
     * Falls back to ablation-based importance if unavailable.
     */
    private fun runExplain(interp: Interpreter, features: FloatArray): FloatArray? {
        return try {
            val inputArr = featuresToInputArray(features)
            val outputArr = Array(1) { FloatArray(FeatureExtractor.N_FEATURES) }
            interp.runSignature(
                mapOf("x" to inputArr),
                mutableMapOf<String, Any>("importances" to outputArr),
                "explain",
            )
            outputArr[0]
        } catch (e: Exception) {
            Log.w(TAG, "explain signature unavailable (${e.message}) — using ablation XAI fallback")
            runAblationImportance(interp, features)
        }
    }

    /**
     * Gradient-free feature importance
     */
    private fun runAblationImportance(interp: Interpreter, features: FloatArray): FloatArray? {
        return try {
            val baseline = runInferenceRaw(interp, features) ?: return null
            val baselineStress = baseline[1]
            FloatArray(FeatureExtractor.N_FEATURES) { i ->
                val perturbed = features.copyOf()
                perturbed[i] = 0f
                val out = runInferenceRaw(interp, perturbed)
                if (out != null) (baselineStress - out[1]).coerceAtLeast(0f) else 0f
            }
        } catch (e: Exception) {
            Log.w(TAG, "Ablation importance also failed: ${e.message}")
            null
        }
    }

    // misc helpers

    private fun FloatArray.extractFeatureAt(featureIdx: Int): Float =
        getOrElse(featureIdx) { 0f }

    private fun buildFeatureNames(): List<String> = listOf(
        "hrv_meanNN", "hrv_SDNN", "hrv_RMSSD", "hrv_pNN50",
        "hrv_LF", "hrv_HF", "hrv_LFHF",
        "eda_scl_mean", "eda_scl_slope", "eda_scr_mean", "eda_scr_std",
        "eda_scr_auc", "eda_scr_peaks", "eda_scr_amp_mean",
        "temp_mean", "temp_std", "temp_slope", "temp_min", "temp_max",
        "acc_mag_mean", "acc_mag_std", "acc_mag_energy", "acc_mag_zcr",
    )

    /** Serialise FloatArray to little-endian bytes for Room BLOB storage. */
    private fun floatArrayToBytes(fa: FloatArray): ByteArray {
        val buf = ByteBuffer.allocate(fa.size * 4).order(ByteOrder.LITTLE_ENDIAN)
        fa.forEach { buf.putFloat(it) }
        return buf.array()
    }
}